name = "NuFlux"
uuid = "efbbe403-48f9-4d1c-bbe5-17d2c19d1ebf"
authors = ["Johannes Schumann <johannes.schumann@fau.de>"]
version = "0.1.0"

[deps]
Corpuscles = "e78a0372-c628-4773-9c8d-eb17d149bf93"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
LRUCache = "8ac3fa9e-de4c-5943-b1dc-09c6b5f20637"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
